Disabled Archim2 due to pin related compile failures
Marlin/src/Marlin.cpp: In function 'void enable_all_steppers()':
Marlin/src/inc/../HAL/HAL_DUE/fastio_Due.h:62:37: error: 'DIO105_WPORT' was not declared in this scope
#define _WRITE(IO, v) do {  if (v) {DIO ## IO ## _WPORT -> PIO_SODR = MASK(DIO ## IO ##_PIN); } \
^
Marlin/src/inc/../HAL/HAL_DUE/fastio_Due.h:92:23: note: in expansion of macro '_WRITE'
#define WRITE(IO, v)  _WRITE(IO, v)
^
Marlin/src/module/stepper_indirection.h:280:36: note: in expansion of macro 'WRITE'
#define E0_ENABLE_WRITE(STATE) WRITE(E0_ENABLE_PIN,STATE)
^
Marlin/src/Marlin.h:105:26: note: in expansion of macro 'E0_ENABLE_WRITE'
#define  enable_E0() E0_ENABLE_WRITE( E_ENABLE_ON)
^
Marlin/src/Marlin.cpp:296:3: note: in expansion of macro 'enable_E0'
enable_E0();
^
Marlin/src/inc/../HAL/HAL_DUE/fastio_Due.h:62:76: error: 'DIO105_PIN' was not declared in this scope
#define _WRITE(IO, v) do {  if (v) {DIO ## IO ## _WPORT -> PIO_SODR = MASK(DIO ## IO ##_PIN); } \