Disable Kossel Pro example config due to compile failure
Marlin/src/HAL/HAL_AVR/../../inc/SanityCheck.h:691:8: error: #error "Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN requires the Z_MIN_PIN to be defined."