Disable Malyan/M200 target due to compile failure
Someone should fix this later

The command "use_example_configs Malyan/M200" exited with 0.
3.81s$ build_marlin_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
In file included from Marlin/src/inc/MarlinConfigPre.h:31:0,
from Marlin/src/inc/MarlinConfig.h:26,
from Marlin/src/Marlin.h:25,
from Marlin/src/Marlin.cpp:31:
Marlin/src/Marlin.cpp: In function 'bool pin_is_protected(pin_t)':
Marlin/src/inc/../../Configuration_adv.h:215:25: error: 'PB8' was not declared in this scope
#define E0_AUTO_FAN_PIN PB8
^
Marlin/src/inc/../pins/pins.h:556:32: note: in expansion of macro 'E0_AUTO_FAN_PIN'
#define _H0_PINS HEATER_0_PIN, E0_AUTO_FAN_PIN, analogInputToDigitalPin(TEMP_0_PIN),
^
Marlin/src/inc/../pins/pins.h:749:5: note: in expansion of macro '_H0_PINS'
_H0_PINS _H1_PINS _H2_PINS _H3_PINS _H4_PINS \
^
Marlin/src/Marlin.cpp:276:49: note: in expansion of macro 'SENSITIVE_PINS'
static const pin_t sensitive_pins[] PROGMEM = SENSITIVE_PINS;
^
*** [.pioenvs/megaatmega2560/src/src/Marlin.o] Error 1
========================== [ERROR] Took 3.63 seconds ==========================
================================== [SUMMARY] ==================================
Environment megaatmega2560          	[ERROR]
Environment megaatmega1280          	[SKIP]
Environment anet10                  	[SKIP]
Environment DUE                     	[SKIP]
Environment LPC1768                 	[SKIP]
Environment LPC1768_debug_and_upload	[SKIP]
Environment rambo                   	[SKIP]
Environment sanguino_atmega644p     	[SKIP]
Environment STM32F1                 	[SKIP]
Environment teensy20                	[SKIP]
Environment teensy35                	[SKIP]
========================== [ERROR] Took 3.64 seconds ==========================
The command "build_marlin_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}" exited with 1.
.